/*
Do not edit this file manually, because it is generated by tools 'sr'.
*/
import S2Base from "strongres"
class system extends S2Base {
    public get groupKey(): string {
        return "strongres.system";
    }
    public format_confirm_delete(args: any): string {
        return this.formatSRValueWithArgs("confirm_delete", args);
    }

    /**
    * 查找键为'delete_ok'，类似 删除用户成功。 的本地化字符串。
    */
    public get delete_ok(): string {
        return this.getSRValue("delete_ok");
    }
}
export default new system();