
export const LineSplitChar = "\r\n";
export const PackName = "strongres";
export const BinName="sr";
export const StrongTypeDocs = "Do not edit this file manually, because it is generated by tools 'sr'.";
export const PackageJsonName = "package.json";

